### ISSUE TITLE
Validator should be able to reject record

### ISSUE THREAD

**Issue by Vince-Egan** [kartoza/LEDET_BIMS#266] opened 2018-08-21 08:27 UTC
We need to have a button available to the validator that rejects/queries a record (we might need a message field to record why it is being queried?) The record should fall off the validator's list and reappear on the data uploaders 'upload' list. The uploader should have the option to delete the record.

**Comment by gubuntu** [comment] 2018-08-22 11:38
duplicate of https://github.com/kartoza/django-bims/issues/233 
and https://github.com/kartoza/django-bims/issues/262

**Closed by gubuntu** 2018-08-22 11:38 UTC
