### ISSUE TITLE
backup and restore flushes data

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/LEDET_BIMS#190] opened 2018-07-18 08:08 UTC
# problem 
When doing a geonode restore it flushes the data for all the Ledet bims modules. And also breaks the site. 

Procedure 
* python manage.py restore --backup-file=backup.zip
* python manage.py migrate_baseurl --source-address=lbimsgis.kartoza.com --target-address=testing.limpopobims.kartoza.com
```
Document #None does not exit.
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/base/management/commands/restore.py", line 373, in handle
    call_command('loaddata', fixture_file, app_label=app_name)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 205, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/src/geonode/geonode/documents/models.py", line 187, in post_save_document
    reverse('document_download', args=(instance.id,)))
  File "/usr/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Problem installing fixture '/tmp/restore/2018-07-17_105643/documents.json': Reverse for 'document_download' with arguments '(None,)' not found. 1 pattern(s) tried: ['documents/(?P<docid>\\d+)/download/?$']
WARNING: No valid fixture data found for 'documents'.
Reactivating GeoNode Signals...
...done!
```
```
HINT: If you migrated from another site, do not forget to run the command 'migrate_baseurl' to fix Links
 e.g.:  DJANGO_SETTINGS_MODULE=my_geonode.settings python manage.py migrate_baseurl --source-address=my-host-dev.geonode.org --target-address=my-host-prod.geonode.org
Restore finished. Please find restored files and dumps into:
Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/src/geonode/geonode/base/management/commands/restore.py", line 373, in handle
    call_command('loaddata', fixture_file, app_label=app_name)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
    return super(Command, self).handle(*fixture_labels, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
    self.load_label(fixture_label)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 175, in load_label
    obj.save(using=self.using)
  File "/usr/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 205, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/models/base.py", line 846, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/usr/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/usr/src/geonode/geonode/documents/models.py", line 187, in post_save_document
    reverse('document_download', args=(instance.id,)))
  File "/usr/local/lib/python2.7/site-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Problem installing fixture '/tmp/restore/2018-07-17_105643/documents.json': Reverse for 'document_download' with arguments '(None,)' not found. 1 pattern(s) tried: ['documents/(?P<docid>\\d+)/download/?$']
```

# Solution
We need a way to preserve the current context of the site (fish data etc stored in Django tables and permissions)

required by #158

**Comment by gubuntu** [comment] 2018-07-18 10:11
@lucernae @dimasciput the architecture and orchestration need to be tweaked to allow this restore to happen cleanly asap

**Comment by lucernae** [comment] 2018-07-19 05:01
Where can I have this backup.zip (does it have fish data?).
From the stacktrace alone, it seems that the problem is just from the documents model of geonode.

**Comment by NyakudyaA** [comment] 2018-07-19 06:57
@lucernae cc @dimasciput  this was just another error I found out about the restore. You can access the backup from the http://rancher.kartoza.com:8080/env/1a11712/apps/stacks/1st704/services/1s2305/containers
Data path: `/data/2018-07-17_105643.zip`

**Comment by lucernae** [comment] 2018-07-20 06:49
Hi, I analyze the issue and here's what I found:

- [ ] When you restore from a geonode backup, it will flush all existing data in geonode (db, static, geoserver data, and templates). So it was expected that all existing data in this BIMS will be gone too. It was expected by geonode design, and we should not change this.
- [ ] With regards to BIMS model, it was possible to override geonode's restore command with another restore command. For example, this restore command will dump current BIMS data, and restore it again after geonode restore. But some models depend on Geonode's model (User or Profile model), so the foreign key will be broken and is not possible to load the data from django fixture, because BIMS use previous user data, but now we restore user data from another site. Just another note, this is only a problem when you try to move data from other geonode instance (independent or non BIMS). If we restore from BIMS periodic backup of itself. We have no such problem. 
- [ ] If we only care about periodic backup, we don't have to override geonode's restore command. We can just give different settings for what models needs to be backed up.
- [ ] The error above comes from a bug in GeoNode. They try to execute post_save signals because we have non empty document data. When it was executed, the data is raw, it has no id, only pk. Post save signals tried to reverse the url and it needs id, but it can't find it. So that's the error. GeoNode team attempted to disconnect the signals before restoring, but they forget it didn't affect this process because they load the fixture using another management command (which will have the signals).
- [ ] We can fix this and submit PR for upstream, but it won't be readily available for BIMS because we use image from geosolusionsit stable branch. My current best advise will be for us to use our current geonode-2.8.x-qgis_server branch. However that's also not stable yet, but it's the best we have a.t.m.

I concluded this is a big blocker/complicated issue and should be prioritezed to work on first on GeoSAFE WB project team. I imagine it might take 2/3 days for me to find and implement the fix before it is available to BIMS. The adaptation in BIMS is probably the easy part.

**Comment by gubuntu** [comment] 2018-07-20 10:06
I don't completely understand but thanks for analysing @lucernae 

In this case we need a once-off restore from an independent GeoNode, provided we can guarantee that the content keeps its integrity when it gets transferred to staging and production (or it will be a once-off to each of those too). Once in production at LEDET it will be maintained by final users (next week!)

So can we do the restore / transfer without waiting for this fix?

And will it be an essential fix even for GeoSAFE?

**Comment by dimasciput** [comment] 2018-07-22 07:39
@NyakudyaA @gubuntu, like @lucernae suggested in point 2, I created a temporary geonode restore command  : 
https://github.com/kartoza/django-bims/pull/154

I managed to restore the geonode data on my machine: 
![screen shot 2018-07-22 at 2 34 17 pm](https://user-images.githubusercontent.com/1979569/43043380-cd8a4588-8dbc-11e8-84f1-b63f23eff3ea.png)

But when I try to open one of the layer, I got this error message : 
![screen shot 2018-07-22 at 2 34 23 pm](https://user-images.githubusercontent.com/1979569/43043381-d8978602-8dbc-11e8-9ca5-1beda122f322.png)

**Comment by dimasciput** [comment] 2018-07-23 06:40
@NyakudyaA Hi Admire, that's because django error from our end, basically we use MIDDLEWARE but geonode uses MIDDLEWARE_CLASSES. That has been fixed, and now my current issue is the geoserver data is still empty.

**Comment by lucernae** [comment] 2018-07-24 08:10
> So can we do the restore / transfer without waiting for this fix?

For related files like media and geoserver files, we have to copy over from origin, or just take it from the geonode backup zip files.
For database transfer, we can just use pgdump to create database backup from origin. Pgrestore to restore it to BIMS, then allow GeoNode to run first to apply migrations.

**Comment by gubuntu** [comment] 2018-08-07 20:27
@NyakudyaA are you happy this is sorted now? Please close is so

**Closed** 2018-08-13 11:01 UTC
Labels: bug, in progress
