### ISSUE TITLE
Landing Page - Icons and Numbers

### ISSUE THREAD

**Issue by cchristelis** [kartoza/LEDET_BIMS#262] opened 2018-08-20 11:23 UTC
# Problem

We have a landing page that has duplicate icons and numbers that don't mean anything.

# Proposed Solution

- [x] Update the icons.
- [x] Update the numbers to pull live totals from the DB.

**Comment by gubuntu** [comment] 2018-08-20 11:52
duplicate of #186

**Comment by Vries14** [comment] 2018-09-13 14:45
Closed by #186

**Closed by Vries14** 2018-09-13 14:45 UTC
Labels: bug, testing
